deepcopy stored on module for AK_ArrayDeepCopy
InvestmentSystems/arraykit pull request #53
Opened 2021-06-11 22:28 UTC by flexatone

2021-06-11 22:31 UTC, flexatone commented
This change improves performance from as low as .93% to at least 1.0.
```
cls                     func                    ak                      ref                     ref/ak                  
ArrayDeepcopy           memo_new                18.62973568             19.74299165             1.05975694              
ArrayDeepcopy           memo_shared             0.04034022              0.04228398              1.0481842             
```

2021-06-29 16:56 UTC, brandtbucher requested changes
Nice! Just two small fixes (we haven't checked `m` for `NULL` yet at this point):

2021-06-29 16:56 UTC, brandtbucher commented on src/_arraykit.c
> +        Py_DECREF(m);
```suggestion
        Py_XDECREF(m);
```

2021-06-29 16:56 UTC, brandtbucher commented on src/_arraykit.c
> +        Py_DECREF(m);
```suggestion
        Py_XDECREF(m);
```

2021-09-08 15:41 UTC, flexatone commented on src/_arraykit.c
> +        Py_DECREF(m);
Thanks!

2021-09-08 15:41 UTC, flexatone commented on src/_arraykit.c
> +        Py_DECREF(m);
👍🏽

2021-09-08 16:41 UTC, brandtbucher approved these changes

2021-09-09 00:33 UTC, merged